{% set name = "harlequin-trino" %}
{% set version = "0.1.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/harlequin_trino-{{ version }}.tar.gz
  sha256: bea556eb232d69aabb375b2c62d6624e74d4b68fd8017dd6481dbcabcdbf618d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - poetry-core
    - pip
  run:
    - python >={{ python_min }},<4.0
    - harlequin >=1.7,<3
    - trino-python-client >=0.327.0,<0.328.0

test:
  imports:
    - harlequin_trino
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://harlequin.sh
  dev_url: https://github.com/TylerHillery/harlequin-trino
  summary: A Harlequin adapter for Trino.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - conda-forge/harlequin
